framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 3
          # milliseconds delay
          delay: 1000

    routing:
      'SunFinanceGroup\Notificator\AppBundle\Notification\NotificationCommand': async
