services:
    _defaults:
        autowire: true
        autoconfigure: true

    SunFinanceGroup\Notificator\TemplateBundle\Controller\TemplateController:
        tags:
            - { name: controller.service_arguments }

    SunFinanceGroup\Notificator\TemplateService\TemplateRendererInterface:
        alias: SunFinanceGroup\Notificator\TemplateBundle\TwigTemplateRendererAdapter

    SunFinanceGroup\Notificator\TemplateBundle\TwigTemplateRendererAdapter: ~

    SunFinanceGroup\Notificator\TemplateBundle\TemplateRepositoryInterface:
        alias: SunFinanceGroup\Notificator\TemplateBundle\DoctrineTemplateRepository
    SunFinanceGroup\Notificator\TemplateBundle\DoctrineTemplateRepository: ~

    SunFinanceGroup\Notificator\App\JsonAPI\Adapters\JMS\JmsDeserializingArgumentValueResolver:
        $metadataFactory: '@jms_serializer.metadata_factory'
    SunFinanceGroup\Notificator\App\JsonAPI\Adapters\JMS\JmsResponseSerializer:
        $metadataFactory: '@jms_serializer.metadata_factory'

    SunFinanceGroup\Notificator\App\JsonAPI\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_subscriber }

    SunFinanceGroup\Notificator\VerificationService\VerificationCodeGeneratorInterface:
        alias: SunFinanceGroup\Notificator\VerificationBundle\VerificationDictionaryBasedCodeGenerator

    SunFinanceGroup\Notificator\VerificationBundle\VerificationDictionaryBasedCodeGenerator:
        arguments:
            $codeLength: '%env(resolve:VERIFICATION_CODE_LENGTH)%'
            $dict:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 9

    SunFinanceGroup\Notificator\VerificationBundle\VerifierInterface:
        alias: SunFinanceGroup\Notificator\VerificationBundle\VerifiedAdapter

    SunFinanceGroup\Notificator\VerificationBundle\VerifiedAdapter:
        arguments:
            $ttlMinutes: '%env(resolve:VERIFICATION_TTL_MINUTES)%'

    SunFinanceGroup\Notificator\VerificationBundle\Controller\VerificationController:
        tags:
            - { name: controller.service_arguments }

    SunFinanceGroup\Notificator\VerificationService\VerifierInterface:
        alias: SunFinanceGroup\Notificator\VerificationService\Verifier
    SunFinanceGroup\Notificator\VerificationService\Verifier: ~

    SunFinanceGroup\Notificator\VerificationService\VerificationRepositoryInterface:
        alias: SunFinanceGroup\Notificator\VerificationBundle\DoctrineVerificationRepositoryAdapter

    SunFinanceGroup\Notificator\VerificationBundle\DoctrineVerificationRepositoryAdapter: ~
