services:
    _defaults:
        autowire: true
        autoconfigure: true

    SunFinanceGroup\Notificator\TemplateBundle\Controller\TemplateController:
        tags:
            - { name: controller.service_arguments }

    SunFinanceGroup\Notificator\TemplateBundle\TwigTemplateRendererAdapter: ~

    SunFinanceGroup\Notificator\TemplateBundle\DoctrineTemplateRepository: ~

    SunFinanceGroup\Notificator\App\JsonAPI\Adapters\JMS\JmsDeserializingArgumentValueResolver:
        $metadataFactory: '@jms_serializer.metadata_factory'

    SunFinanceGroup\Notificator\App\JsonAPI\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_subscriber }
