services:
    _defaults:
        autowire: true
        autoconfigure: true

    SunFinanceGroup\Notificator\TemplateBundle\Controller\TemplateController:
        tags:
            - { name: controller.service_arguments }

    SunFinanceGroup\Notificator\TemplateService\TemplateRendererInterface:
        alias: SunFinanceGroup\Notificator\TemplateBundle\TwigTemplateRendererAdapter

    SunFinanceGroup\Notificator\TemplateBundle\TwigTemplateRendererAdapter: ~

    SunFinanceGroup\Notificator\TemplateBundle\TemplateRepositoryInterface:
        alias: SunFinanceGroup\Notificator\TemplateBundle\DoctrineTemplateRepository
    SunFinanceGroup\Notificator\TemplateBundle\DoctrineTemplateRepository: ~

    SunFinanceGroup\Notificator\App\JsonAPI\Adapters\JMS\JmsDeserializingArgumentValueResolver:
        $metadataFactory: '@jms_serializer.metadata_factory'
    SunFinanceGroup\Notificator\App\JsonAPI\Adapters\JMS\JmsResponseSerializer:
        $metadataFactory: '@jms_serializer.metadata_factory'

    SunFinanceGroup\Notificator\App\JsonAPI\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_subscriber }

    SunFinanceGroup\Notificator\VerificationService\VerificationCodeGeneratorInterface:
        alias: SunFinanceGroup\Notificator\VerificationBundle\VerificationDictionaryBasedCodeGenerator

    SunFinanceGroup\Notificator\VerificationBundle\VerificationDictionaryBasedCodeGenerator:
        arguments:
            $codeLength: '%env(resolve:VERIFICATION_CODE_LENGTH)%'
            $dict:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 9

    SunFinanceGroup\Notificator\VerificationBundle\VerifierInterface:
        alias: SunFinanceGroup\Notificator\VerificationBundle\VerifiedAdapter

    SunFinanceGroup\Notificator\VerificationBundle\VerifiedAdapter: ~

    SunFinanceGroup\Notificator\VerificationBundle\Controller\VerificationController:
        tags:
            - { name: controller.service_arguments }

    SunFinanceGroup\Notificator\VerificationService\VerifierInterface:
        alias: SunFinanceGroup\Notificator\VerificationService\Verifier

    SunFinanceGroup\Notificator\VerificationService\Verifier:
        arguments:
            $ttlMinutes: '%env(resolve:VERIFICATION_TTL_MINUTES)%'

    SunFinanceGroup\Notificator\VerificationService\VerificationRepositoryInterface:
        alias: SunFinanceGroup\Notificator\VerificationBundle\DoctrineVerificationRepositoryAdapter

    SunFinanceGroup\Notificator\VerificationBundle\DoctrineVerificationRepositoryAdapter: ~

    SunFinanceGroup\Notificator\AppBundle\Notification\GotifyTransport:
        arguments:
            $guzzle: '@eight_points_guzzle.client.gotify'
            $token: '%env(resolve:GOTIFY_TOKEN)%'

    SunFinanceGroup\Notificator\AppBundle\Notification\EmailTransport: ~

    SunFinanceGroup\Notificator\NotificationService\TransportSelectorInterface:
        alias: SunFinanceGroup\Notificator\AppBundle\Notification\TransportSelector

    SunFinanceGroup\Notificator\AppBundle\Notification\TransportSelector:
        calls:
            - method: registerTransport
              arguments:
                  $channel: 'SMS'
                  $transport: '@SunFinanceGroup\Notificator\AppBundle\Notification\GotifyTransport'
            - method: registerTransport
              arguments:
                  $channel: 'EMAIL'
                  $transport: '@SunFinanceGroup\Notificator\AppBundle\Notification\EmailTransport'

    SunFinanceGroup\Notificator\AppBundle\Notification\NotificationCommandHandler: ~

    SunFinanceGroup\Notificator\AppBundle\Notification\VerificationEventListener: ~

    SunFinanceGroup\Notificator\NotificationService\NotificationRepositoryInterface:
        alias: SunFinanceGroup\Notificator\AppBundle\Notification\DoctrineNotificationRepository

    SunFinanceGroup\Notificator\AppBundle\Notification\DoctrineNotificationRepository: ~

    SunFinanceGroup\Notificator\NotificationService\NotificatorInterface:
        alias: SunFinanceGroup\Notificator\NotificationService\Notificator

    SunFinanceGroup\Notificator\NotificationService\Notificator: ~

    SunFinanceGroup\Notificator\AppBundle\TemplateBridge\RendererInterface:
        alias: SunFinanceGroup\Notificator\AppBundle\TemplateBridge\Renderer

    SunFinanceGroup\Notificator\AppBundle\TemplateBridge\Renderer:
        arguments:
            $guzzle: '@eight_points_guzzle.client.template'